% Generated by lilypond-book
% Options: [printfilename,texidoc,line-width]

\layout {
    line-width = 180 \mm
}
\paper {
	#(set-paper-size "letter")	
}	
\version "2.15.19"
\header
{
	filename = "GoTellItOnTheMountain.ly"
	enteredby = "Gordon Gilbert"
	title = "Go, Tell It on the Mountain"
	subtitle = "" 
	composer = "traditional Spiritual"
	poet = "Negro Spiritual"
	date=""
	copyright = ""
	maintainer = "Gordon Gilbert"
	maintainerEmail = "gord@angel.eicat.ca"
	lastupdated = "2011/Dec/14"
	
}
%shorthand for Skip Lyric

melody =  { 

\override Staff.VerticalAxisGroup #'minimum-Y-extent = #'(-4 . 4)
\time 4/4 \key g \major
\relative {

	b'2 ^ \markup \large \italic "Refrain" b8. a16 g8. e16 d2 g
	fis8 a4 g8 a4 g b8( a) g4 e8( d4.)
	b'2 b8. a16 g8. e16 d2 g4
	c4 b b a8( g) a4 g2. ^ \markup \large \italic "Fine" \bar "||"
	g4 ^\markup \large \italic "Verse" b d d e d b2
	g4 a a g a b2.
	g4 b d d e d b2
	g4 a a g e d2( c') ^ \markup \large \italic "D.C."
	
	 \bar "||"
	
}}

text = \lyricmode {

	Go, tell it on the moun -- tain,
	O -- ver the hills and ev -- ery -- where.
	Go, tell it on the moun -- tain
	That Je -- sus Christ is born!
	While shep -- herds kept their watch -- ing
	O'er si -- lent flocks by night,
	Be -- hold, through -- out the hea -- vens
	There shone a ho -- ly light.
	}

textVerseTwo = \lyricmode {
	_ _ _ _ _ _ _ _ _ _ _ _
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	The shep -- herds feared and trem -- bled
	When lo, a -- bove the earth
	Rang out the an -- gel chor -- us
	That hailed our Sav -- iour's birth!
	}

textVerseThree = \lyricmode {
	_ _ _ _ _ _ _ _ _ _ _ _
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	Down in a lone -- ly man -- ger
	The hum -- ble Christ was born,
	And God sent our sal -- va -- tion
	That bless -- ed Christ -- mas morn.	
	}

accompaniment = \chordmode {    
	g2 c:/g g1 d:7 g2 c4 d
	g2 c:/g g2. c4 g2 d g1
	g g d:7 g
	g g a2:m c d1:7
	}

\score {
	\transpose g e 
  <<
    \context ChordNames \accompaniment
    \context Voice = "one" {
	%\autoBeamOff
        \melody}
    \lyricsto "one" \new Lyrics  \text
    \lyricsto "one" \new Lyrics \textVerseTwo
    \lyricsto "one" \new Lyrics \textVerseThree
  >>
  \layout { }
  \midi  { }
}